name: CI/CD

on:
  pull_request:
    branches:
      - master  # ou la branche que vous souhaitez surveiller

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod-secrets
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install  # ou yarn install

    - name: Build and test
      run: npm run build && npm test  # ou yarn build && yarn test

    - name: Build Docker image
      run: docker build -t ${{ secrets.APP_IMAGE }} .  # adapter le nom de l'image si nécessaire

    - name: Push Docker image to registry
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker tag ${{ secrets.APP_IMAGE }} ${{ secrets.DOCKER_USERNAME }}/${{ secrets.APP_IMAGE }}:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.APP_IMAGE }}:latest
