name: CI/CD

on:
  pull_request:
    branches:
      - dev  # ou la branche que vous souhaitez surveiller

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev-secrets
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build 
      run: npm run build 

    - name: Build Docker image
      run: docker build -t ${{ secrets.APP_IMAGE }} .  # adapter le nom de l'image si nécessaire
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Docker image to registry
      run: |
        docker tag ${{ secrets.APP_IMAGE }} ${{ secrets.DOCKER_USERNAME }}/${{ secrets.APP_IMAGE }}:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.APP_IMAGE }}:latest

    - name: Deploy on cap rover
      run: docker run caprover/cli-caprover:latest caprover deploy --caproverUrl "${{ secrets.CAPROVER_URL }}" --appToken "${{ secrets.APP_TOKEN }}" --caproverApp "${{ secrets.APP_NAME }}" --imageName "${{ secrets.APP_IMAGE }}"
